#!/bin/bash
##
# $ source usr/usage
##

export DN=/dev/null

assert_exit_0 () { statement=$*
    $statement 1>$DN
    xit=$?
    if test "$xit" == "0"
    then
        echo -n .
    else
        echo "$xit != 0"
        return 1
    fi
}

assert_exit_n () { code=$1; statement=${*:2}
    $statement 2>$DN
    xit=$?
    if test "$xit" == "$code"
    then
        echo -n .
    else
        echo "$xit != $code"
        return 1
    fi
}

assert_verb () { verb=$1; original=$2; expected=$3
    actual=$($verb "$original")
    test "$expected" == "$actual"\
    && echo -n .\
    || {
        echo "$verb '$original'"
        echo "== $actual"
        echo "!= $expected"
        return 1;
    };
}

export -f assert_exit_0 assert_exit_n assert_verb
