name: "gwind"
version: 0.7.3
github: "rik-routine/gwind"
license: "GPL"
license-file: "etc/license"
author: "Rik Howard"
maintainer: "rik@lrbh.info"
copyright: "2025 Rik Howard"
synopsis: "GWind is a tool for accomplishing some foundational tasks on GCP."
category: "Experimental"
description: "Please see the read-me on GitHub at <https://github.com/rik-routine/gwind>"

extra-doc-files:
- readMe.md
- artisan.md
- builder.md
- changes.md

dependencies:
- base >= 4.7 && < 5
- text >= 2.1.1 && < 2.2
- rho-system >= 0.2.0 && < 0.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing

library:
  source-dirs: src
  dependencies:
  - aeson >= 2.2.3.0 && < 2.3
  - aeson-pretty >= 0.8.10 && < 8.11
  - bytestring >= 0.12.1.0 && < 0.13
  - wreq >= 0.5.4.3 && < 0.6
  - http-types >= 0.12.4 && < 0.13
  - process >= 1.6.25.0 && < 1.7
  - lens >= 5.3.4 && < 5.4
  - split >= 0.2.5 && < 0.3

executables:
  gwind-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neat-interpolation >= 0.5.1.4 && < 0.5.2
    - gwind

tests:
  gwind-test:
    main: Test.hs
    source-dirs: tst
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gwind
    - HUnit
