name: Tag Pipeline

on:
  push:
    tags: ['*']

jobs:

  linux-amd:
    uses: .github/workflows/build.yaml
    with:
      os-name: ubuntu-latest
      program: gwind
      version: ${{github.ref_name}}

  darwin-arm:
    uses: .github/workflows/build.yaml
    with:
      os-name: macos-latest
      program: gwind
      version: ${{github.ref_name}}

  release:
    uses: .github/workflows/release.yaml
    needs: [linux-amd, darwin-arm]
    with:
      linux_amd_name: ${{needs.linux-amd.artefact_name}}
      darwin_arm_name: ${{needs.darwin-arm.artefact_name}}
