name: Pipeline

on: push

jobs:
  entrance:
    runs-on: ubuntu-latest
    steps:
    - name: foo
      run: |
        echo ${{github.ref_name}}
        echo ${{github.event}}

  linux-amd-cache:
    uses: .github/workflows/cache.yaml
    with:
      os-name: ubuntu-latest

#  darwin-arm-cache:
#    uses: ./.github/workflows/cache.yaml@main
#    with:
#      os-name: macos-latest
#
#  linux-amd-build:
#    uses: .github/workflows/build.yaml
#    needs: linux-amd-cache
#    with:
#      os-name: ubuntu-latest
#      program: gwind
#      version: ${{github.ref_name}}
#
#  darwin-arm-build:
#    uses: .github/workflows/build.yaml
#    needs: darwin-arm-cache
#    with:
#      os-name: macos-latest
#      program: gwind
#      version: ${{github.ref_name}}
#
#  release:
#    uses: .github/workflows/release.yaml
#    needs: [linux-amd-build, darwin-arm-build]
#    with:
#      linux-amd-name: ${{needs.linux-amd.artefact_name}}
#      darwin-arm-name: ${{needs.darwin-arm.artefact_name}}
